### ISSUE TITLE
Version 1.2.1 doesn't work with docker alpine image

### ISSUE THREAD

**Issue by xiao-x-s** [pyrogram/tgcrypto#12]
Using `python:3.6-alpine` image and getting the following behavior when attempting to install latest TgCrypto

```
pip install TgCrypto==1.2.1
```

```
ERROR: Could not find a version that satisfies the requirement TgCrypto==1.2.1 (from versions: 0.0.1b1, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.1.1, 1.2.0)
ERROR: No matching distribution found for TgCrypto==1.2.1
```

So I can only use TgCrypto 1.2.0 instead.

**Comment by delivrance** [comment]
Did you solve the issue? It looks like an old cache hit. Try with `pip install -U tgcrypto --no-cache-dir`.
