### ISSUE TITLE
Add wheels for Python 3.9

### ISSUE THREAD

**Issue by Senpos** [pyrogram/tgcrypto#15]
Hello!

Python 3.9 released on October 5th.

It would be cool if we could install TgCrypto from wheels. :-)
Especially, this is useful for Windows users, as it is pretty common not to have a compiler installed, as it is quite bulky. 😿

At the moment. TgCrypto has wheels for Python versions from 3.5 to 3.8.

Please, let me know if I can help you with this somehow!

**Comment by delivrance** [comment]
Done! https://github.com/pyrogram/tgcrypto/releases/tag/v1.2.2
