### ISSUE TITLE
AttributeError: module 'tgcrypto' has no attribute 'ige_encrypt'

### ISSUE THREAD

**Issue by matiniamirhossein** [pyrogram/tgcrypto#2]
Hello,
Using the same code as in README, we are getting this error:
AttributeError: module 'tgcrypto' has no attribute 'ige_encrypt'
This also stands for other methods:
AttributeError: module 'tgcrypto' has no attribute 'ige_decrypt'

Issue happens on the latest version: 1.1.1
Solved via these commands:
```
pip3 uninstall pyrogram
pip3 install 'tgcrypto<1.1.1'
```
Code:
```
import os
import tgcrypto

data = os.urandom(10 * 1024 * 1024)  # 10 MB of random data
key = os.urandom(32)  # Random Key
iv = os.urandom(32)  # Random IV

ige_encrypted = tgcrypto.ige_encrypt(data, key, iv)
ige_decrypted = tgcrypto.ige_decrypt(ige_encrypted, key, iv)

assert data == ige_decrypted
```

**Comment by matiniamirhossein** [comment]
@delivrance Thanks. But I think they should be deprecated for a while then removed. A lot of source codes does not work now when installing.

**Comment by delivrance** [comment]
@matiniamirhossein You are right about the deprecation thing, but I planned to update Pyrogram too (which I did already) and you are supposed to use the latest version! I think you just stumbled on this while I was busy upgrading, which took longer than usual.
