### ISSUE TITLE
How can i hook encryption methods?

### ISSUE THREAD

**Issue by Numenorean** [pyrogram/tgcrypto#20]
I need to hook encryption/decryption methods to get some keys. How can i do that? i found out that i need modify some .c and .h files, but even if i do that i don't know how to build it myself. I've installed build tools, but i still have this error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
What should i do?

**Comment by Numenorean** [comment]
anyone here?

**Comment by delivrance** [comment]
Hi. The issue section on GitHub is for actual issues with the library, it's not a forum for questions.
If you'd like to ask a question, do so at [StackOverflow](https://stackoverflow.com/questions/ask) or join the [community](https://t.me/pyrogram).
