### ISSUE TITLE
Whl file incompatible with armv6l

### ISSUE THREAD

**Issue by richard-scott** [pyrogram/tgcrypto#26]
I get an "Illegal instruction" error with v1.2.3 on a RPi 1 b (armv6l). This error goes away if I install from source and get pip to compile for me (with --no-binary).

Edit: It only seems to be an issue with Python 3.7 and 3.9. The others are ok:

```
Y - 3.10.1
Y - 3.6.8
N - 3.7.9
Y - 3.8.9
N - 3.9.9
```

**Comment by richard-scott** [comment]
Closing as not 100% sure it's not my setup, as rolling back to 1.2.2 gives me the same error in Python 3.7.9.

**Comment by delivrance** [comment]
The CI build tools being used don't seem to support this old architecture, hence pre-built wheels are not provided. Compiling locally (i.e. using pip's `--no-binary` option) is a viable solution for such old architectures.
