### ISSUE TITLE
Documentation needs updating for v1.1.1

### ISSUE THREAD

**Issue by richard-scott** [pyrogram/tgcrypto#3]
I've noticed that things have changed in v1.1.1 compared to v1.0.4.

- ctr_encrypt -> ctr256_encrypt
- ctr_decrypt -> ctr256_decrypt
- ige_encrypt -> ige256_encrypt
- ige_decrypt -> ige256_decrypt

The documentation needs updating to reflect the recent changes.
Also, the image url's used on the README are wrong.

**Comment by delivrance** [comment]
Yep, I definitely have to take more care of tgcrypto's readme.

**Comment by delivrance** [comment]
Done! I've updated the logo as well.
