### ISSUE TITLE
error: Microsoft Visual C++ 14.0 is required

### ISSUE THREAD

**Issue by john685** [pyrogram/tgcrypto#9]
when i want to install TgCrypto on windows 10...i see this error and it can't be install...
details of error:

Collecting TgCrypto==1.2.0
  Using cached https://files.pythonhosted.org/packages/30/e6/65b15e0e6013c232f6236b70bf968c2bbc74c26fbb31ad3378d67cba3498/TgCrypto-1.2.0.tar.gz
Installing collected packages: TgCrypto
  Running setup.py install for TgCrypto: started
    Running setup.py install for TgCrypto: finished with status 'error'
    Complete output from command D:\Projects\Python\SNPgram\venv\Scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\saied\\AppData\\Local\\Temp\\pycharm-packaging\\TgCrypto\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-record-qakbdd9q\install-record.txt --single-version-externally-managed --compile --install-headers D:\Projects\Python\SNPgram\venv\include\site\python3.8\TgCrypto:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.8
    creating build\lib.win-amd64-3.8\tests
    copying tests\__init__.py -> build\lib.win-amd64-3.8\tests
    creating build\lib.win-amd64-3.8\tests\cbc
    copying tests\cbc\test_cbc.py -> build\lib.win-amd64-3.8\tests\cbc
    copying tests\cbc\__init__.py -> build\lib.win-amd64-3.8\tests\cbc
    creating build\lib.win-amd64-3.8\tests\ctr
    copying tests\ctr\test_ctr.py -> build\lib.win-amd64-3.8\tests\ctr
    copying tests\ctr\__init__.py -> build\lib.win-amd64-3.8\tests\ctr
    creating build\lib.win-amd64-3.8\tests\ige
    copying tests\ige\test_ige.py -> build\lib.win-amd64-3.8\tests\ige
    copying tests\ige\__init__.py -> build\lib.win-amd64-3.8\tests\ige
    warning: build_py: byte-compiling is disabled, skipping.
    
    running build_ext
    building 'tgcrypto' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
    

and when i install visual c++ 14.0 ... This error still exists...

**Comment by delivrance** [comment]
This is not an issue with tgcrypto itself, but rather with the fact that you are using python 3.8. You either need to get MSVC recognised properly or wait for me to add support for python 3.8.

**Comment by delivrance** [comment]
New wheels have been uploaded to support Python 3.8.
Please try again now with `pip3 install -U tgcrypto --no-cache-dir`
